// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VotoElectonico.Data;

#nullable disable

namespace VotoElectonico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260108015919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VotoElectonico.Models.Candidato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("NombreEnPapeleta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrdenEnLista")
                        .HasColumnType("integer");

                    b.Property<int>("PartidoPoliticoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidoPoliticoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("VotoElectonico.Models.DetalleVoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<int?>("PartidoPoliticoId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("VotoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("PartidoPoliticoId");

                    b.HasIndex("VotoId");

                    b.ToTable("DetalleVoto", t =>
                        {
                            t.HasCheckConstraint("CK_DetalleVoto_SiNoBlancoSinIds", "(\"Tipo\" NOT IN (2,3,4)) OR (\"CandidatoId\" IS NULL AND \"PartidoPoliticoId\" IS NULL)");

                            t.HasCheckConstraint("CK_DetalleVoto_SoloUno", "NOT (\"PartidoPoliticoId\" IS NOT NULL AND \"CandidatoId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_DetalleVoto_TipoCandidato", "(\"Tipo\" <> 0) OR (\"CandidatoId\" IS NOT NULL AND \"PartidoPoliticoId\" IS NULL)");

                            t.HasCheckConstraint("CK_DetalleVoto_TipoPartido", "(\"Tipo\" <> 1) OR (\"PartidoPoliticoId\" IS NOT NULL AND \"CandidatoId\" IS NULL)");

                            t.HasCheckConstraint("CK_DetalleVoto_TipoSinIds", "(\"Tipo\" IN (2,3,4)) OR (\"Tipo\" IN (0,1)) OR (1=1)");
                        });
                });

            modelBuilder.Entity("VotoElectonico.Models.HistorialVotacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCertificado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaSufragioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.HasIndex("UsuarioId", "ProcesoElectoralId")
                        .IsUnique();

                    b.ToTable("HistorialVotaciones");
                });

            modelBuilder.Entity("VotoElectonico.Models.PartidoPolitico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("NombreLista")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumeroLista")
                        .HasColumnType("integer");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("PartidoPolitico");
                });

            modelBuilder.Entity("VotoElectonico.Models.ProcesoElectoral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxSeleccionNominal")
                        .HasColumnType("integer");

                    b.Property<int?>("ModalidadPresidencial")
                        .HasColumnType("integer");

                    b.Property<bool>("PermiteNominal")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermitePlancha")
                        .HasColumnType("boolean");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProcesosElectorales");
                });

            modelBuilder.Entity("VotoElectonico.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<string>("NombresCompletos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Parroquia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VotoElectonico.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CantonVotante")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaIngresoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GeneroVotante")
                        .HasColumnType("integer");

                    b.Property<string>("HashSeguridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParroquiaVotante")
                        .HasColumnType("text");

                    b.Property<string>("PayloadCifradoBase64")
                        .HasColumnType("text");

                    b.Property<int>("ProcesoElectoralId")
                        .HasColumnType("integer");

                    b.Property<string>("ProvinciaVotante")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("VotoElectonico.Models.Candidato", b =>
                {
                    b.HasOne("VotoElectonico.Models.PartidoPolitico", "Partido")
                        .WithMany("Candidatos")
                        .HasForeignKey("PartidoPoliticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithOne("InfoCandidatura")
                        .HasForeignKey("VotoElectonico.Models.Candidato", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.DetalleVoto", b =>
                {
                    b.HasOne("VotoElectonico.Models.Candidato", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId");

                    b.HasOne("VotoElectonico.Models.PartidoPolitico", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoPoliticoId");

                    b.HasOne("VotoElectonico.Models.Voto", "Voto")
                        .WithMany("Detalles")
                        .HasForeignKey("VotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Partido");

                    b.Navigation("Voto");
                });

            modelBuilder.Entity("VotoElectonico.Models.HistorialVotacion", b =>
                {
                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", "Proceso")
                        .WithMany("HistorialLog")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithMany("HistorialDeVotaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.PartidoPolitico", b =>
                {
                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", "Proceso")
                        .WithMany("PartidosInscritos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("VotoElectonico.Models.Voto", b =>
                {
                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", "Proceso")
                        .WithMany("UrnaDeVotos")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proceso");
                });

            modelBuilder.Entity("VotoElectonico.Models.PartidoPolitico", b =>
                {
                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("VotoElectonico.Models.ProcesoElectoral", b =>
                {
                    b.Navigation("HistorialLog");

                    b.Navigation("PartidosInscritos");

                    b.Navigation("UrnaDeVotos");
                });

            modelBuilder.Entity("VotoElectonico.Models.Usuario", b =>
                {
                    b.Navigation("HistorialDeVotaciones");

                    b.Navigation("InfoCandidatura");
                });

            modelBuilder.Entity("VotoElectonico.Models.Voto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
