// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VotoElectonico.Data;

#nullable disable

namespace VotoElectonico.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260203170236_AddPublicTokenToComprobante")]
    partial class AddPublicTokenToComprobante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VotoElectonico.Models.Candidato", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PartidoListaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PartidoListaId");

                    b.HasIndex("EleccionId", "Activo");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("VotoElectonico.Models.CodigoVotacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MostradoAlJefeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProcesoElectoralId", "Usado");

                    b.HasIndex("ProcesoElectoralId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("CodigosVotacion");
                });

            modelBuilder.Entity("VotoElectonico.Models.ComprobanteVoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrevoMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EnviadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorEnvio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("EstadoEnvio")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneradoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JefeJuntaUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JuntaId")
                        .HasColumnType("uuid");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.Property<string>("PublicToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicTokenExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("EstadoEnvio");

                    b.HasIndex("JefeJuntaUsuarioId");

                    b.HasIndex("JuntaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProcesoElectoralId", "UsuarioId");

                    b.ToTable("ComprobantesVoto");
                });

            modelBuilder.Entity("VotoElectonico.Models.Eleccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxSeleccionIndividual")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProcesoElectoralId", "Tipo");

                    b.ToTable("Elecciones");
                });

            modelBuilder.Entity("VotoElectonico.Models.EnvioResultadosJunta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnviadoPorJefeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EnviadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("JuntaId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PayloadCifradoBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnviadoPorJefeId");

                    b.HasIndex("JuntaId");

                    b.HasIndex("ProcesoElectoralId", "JuntaId", "EnviadoUtc");

                    b.ToTable("EnviosResultadosJunta");
                });

            modelBuilder.Entity("VotoElectonico.Models.Junta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("JefeJuntaUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parroquia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Recinto")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("JefeJuntaUsuarioId");

                    b.ToTable("Juntas");
                });

            modelBuilder.Entity("VotoElectonico.Models.PadronRegistro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JuntaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VerificadoPorJefeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("VerificadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VotoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("YaVoto")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("JuntaId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VerificadoPorJefeId");

                    b.HasIndex("ProcesoElectoralId", "JuntaId");

                    b.HasIndex("ProcesoElectoralId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("PadronRegistros");
                });

            modelBuilder.Entity("VotoElectonico.Models.PartidoLista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId", "Codigo")
                        .IsUnique();

                    b.ToTable("PartidosListas");
                });

            modelBuilder.Entity("VotoElectonico.Models.ProcesoElectoral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("InicioUtc", "FinUtc");

                    b.ToTable("ProcesosElectorales");
                });

            modelBuilder.Entity("VotoElectonico.Models.ResultadoAgregado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CandidatoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer");

                    b.Property<string>("DimensionValor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Opcion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("PartidoListaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.Property<long>("Votos")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("ProcesoElectoralId", "EleccionId", "Dimension", "DimensionValor");

                    b.ToTable("ResultadosAgregados");
                });

            modelBuilder.Entity("VotoElectonico.Models.TwoFactorSesion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BrevoMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer");

                    b.Property<int>("MaxIntentos")
                        .HasColumnType("integer");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UsadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "CreadoUtc");

                    b.ToTable("TwoFactorSesiones");
                });

            modelBuilder.Entity("VotoElectonico.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Canton")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Parroquia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Provincia")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("VotoElectonico.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "Rol");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("VotoElectonico.Models.VotoAnonimo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CipherTextBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EleccionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EmitidoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JuntaId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NonceBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcesoElectoralId")
                        .HasColumnType("uuid");

                    b.Property<string>("TagBase64")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EleccionId");

                    b.HasIndex("JuntaId", "EmitidoUtc");

                    b.HasIndex("ProcesoElectoralId", "EleccionId");

                    b.ToTable("VotosAnonimos");
                });

            modelBuilder.Entity("VotoElectonico.Models.Candidato", b =>
                {
                    b.HasOne("VotoElectonico.Models.Eleccion", "Eleccion")
                        .WithMany("Candidatos")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.PartidoLista", "PartidoLista")
                        .WithMany("Candidatos")
                        .HasForeignKey("PartidoListaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Eleccion");

                    b.Navigation("PartidoLista");
                });

            modelBuilder.Entity("VotoElectonico.Models.CodigoVotacion", b =>
                {
                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany()
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProcesoElectoral");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.ComprobanteVoto", b =>
                {
                    b.HasOne("VotoElectonico.Models.Eleccion", null)
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", "JefeJuntaUsuario")
                        .WithMany()
                        .HasForeignKey("JefeJuntaUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Junta", "Junta")
                        .WithMany()
                        .HasForeignKey("JuntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", null)
                        .WithMany()
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JefeJuntaUsuario");

                    b.Navigation("Junta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.Eleccion", b =>
                {
                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany("Elecciones")
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcesoElectoral");
                });

            modelBuilder.Entity("VotoElectonico.Models.EnvioResultadosJunta", b =>
                {
                    b.HasOne("VotoElectonico.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("EnviadoPorJefeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Junta", null)
                        .WithMany()
                        .HasForeignKey("JuntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", null)
                        .WithMany()
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VotoElectonico.Models.Junta", b =>
                {
                    b.HasOne("VotoElectonico.Models.Usuario", "JefeJuntaUsuario")
                        .WithMany()
                        .HasForeignKey("JefeJuntaUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JefeJuntaUsuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.PadronRegistro", b =>
                {
                    b.HasOne("VotoElectonico.Models.Junta", "Junta")
                        .WithMany()
                        .HasForeignKey("JuntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", "ProcesoElectoral")
                        .WithMany()
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VerificadoPorJefeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Junta");

                    b.Navigation("ProcesoElectoral");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.PartidoLista", b =>
                {
                    b.HasOne("VotoElectonico.Models.Eleccion", "Eleccion")
                        .WithMany("Listas")
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleccion");
                });

            modelBuilder.Entity("VotoElectonico.Models.ResultadoAgregado", b =>
                {
                    b.HasOne("VotoElectonico.Models.Eleccion", null)
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", null)
                        .WithMany()
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VotoElectonico.Models.TwoFactorSesion", b =>
                {
                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.UsuarioRol", b =>
                {
                    b.HasOne("VotoElectonico.Models.Usuario", "Usuario")
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VotoElectonico.Models.VotoAnonimo", b =>
                {
                    b.HasOne("VotoElectonico.Models.Eleccion", null)
                        .WithMany()
                        .HasForeignKey("EleccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.Junta", null)
                        .WithMany()
                        .HasForeignKey("JuntaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotoElectonico.Models.ProcesoElectoral", null)
                        .WithMany()
                        .HasForeignKey("ProcesoElectoralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("VotoElectonico.Models.Eleccion", b =>
                {
                    b.Navigation("Candidatos");

                    b.Navigation("Listas");
                });

            modelBuilder.Entity("VotoElectonico.Models.PartidoLista", b =>
                {
                    b.Navigation("Candidatos");
                });

            modelBuilder.Entity("VotoElectonico.Models.ProcesoElectoral", b =>
                {
                    b.Navigation("Elecciones");
                });

            modelBuilder.Entity("VotoElectonico.Models.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
